version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
        MONGODB_URI: ${MONGODB_URI}
        RESEND_API_KEY: ${RESEND_API_KEY}
    environment:
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      MONGODB_URI: ${MONGODB_URI}
      RESEND_API_KEY: ${RESEND_API_KEY}
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./components.json:/app/components.json
      - ./next.config.mjs:/app/next.config.mjs
      - ./nodemon.json:/app/nodemon.json
      - ./postcss.config.cjs:/app/postcss.config.cjs
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.server.json:/app/tsconfig.server.json
      - ./.env:/app/.env
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
    restart: unless-stopped

networks:
  default:
    external: true
    name: esu-network
